### ISSUE TITLE
No events survived pre-processing, check DataFetcher and event quality

### ISSUE THREAD

**Issue by echavess** [d-chambers/Detex#38]
Hi Chambers, 

I recently installed the code and I am trying to run the intro example you provided in the website. However, I am having some issues when I call the function createCluster():

```
Cannot remove response without a valid inventoryArg, setting removeResponse to False
Starting IO operations and data checks
/opt/anaconda/lib/python3.5/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)
Traceback (most recent call last):
  File "Intro_detex.py", line 5, in <module>
    cl = detex.createCluster(CCreq=0)
  File "/opt/anaconda/lib/python3.5/site-packages/detex-1.0.8-py3.5.egg/detex/construct.py", line 122, in createCluster
    detex.log(__name__, msg, level='error')
  File "/opt/anaconda/lib/python3.5/site-packages/detex-1.0.8-py3.5.egg/detex/__init__.py", line 138, in log
    raise e(msg)
Exception: No events survived pre-processing, check DataFetcher and event quality
```

These are lines I am using so far:

```
import detex
detex.getdata.makeDataDirectories()
cl = detex.createCluster(CCreq=0.4)
```

Have you seen this before? Thanks in advance for the help.

**Comment by echavess** [comment]
I have removed the first warning, related to LAPACK, adding the next two lines:

```
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")
```

**Comment by d-chambers** [comment]
Hey @echavess,

Before I answer I should let you know that I have not really done anything with this version of detex for awhile. I have been working on a complete rewrite that will fix a lot of the architectural issues but it is not yet ready to release. The API and implementation will be brand new, so I would be cautious about how much time you invest here. I would checkout [EQCorrScan](https://github.com/eqcorrscan/EQcorrscan) for your cross-correlation/subspace detection needs.

That being said, I am happy to help you out. Are you starting with the intro tutorial? 
You will probably want to setup a conda env to run python 2.7. You then need to install pyqt4 (some advice [here](https://stackoverflow.com/questions/21637922/how-to-install-pyqt4-in-anaconda/40920535)). After that I would try running the notebook in detex/tutorial/Intro because it will have all of the files you need. If you run into import errors you can manually install the missing packages (the setup.py doesn't actually list everything detex needs) until the notebook runs all the way through. Let me know if that works for you.
